default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.8.1
    hooks:
      - id: nbqa-black
        args:
          - "--nbqa-mutate"
          - "--nbqa-config=pyproject.toml"
      - id: nbqa-isort
        args:
          - "--nbqa-mutate"
          - "--nbqa-config=.isort.cfg"
      - id: nbqa-flake8
        args:
          - "--nbqa-config=setup.cfg"
      - id: nbqa-pyupgrade
        args:
          - "--nbqa-mutate"
          - "--py38-plus"
